version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27018:27017"  
    volumes:
      - ./mongo-data:/data/db  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root    
      MONGO_INITDB_ROOT_PASSWORD: example 
    restart: unless-stopped
